@baseUrl = http://localhost:8080
###
{{baseUrl}}/greeting
### b64 de user:password -> dXNlcjpwYXNzd29yZA==
{{baseUrl}}/protectedGreeting
Authorization: ...
###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}
